// Code generated by avro/gen. DO NOT EDIT.
package figchain

import (
	"github.com/hamba/avro/v2"
)

// LoanAppParameters is a generated struct.
type LoanAppParameters struct {
	FailThreshold int     `avro:"FailThreshold" json:"fail_threshold" yaml:"FailThreshold"`
	Revision      *string `avro:"revision" json:"revision" yaml:"Revision"`
}

var schemaLoanAppParameters = avro.MustParse(`{"name":"io.figchain._29dc9532_b13e_4b09_bc86_58427fa3f35d.finance.LoanAppParameters","type":"record","fields":[{"name":"FailThreshold","type":"int"},{"name":"revision","type":["null","string"]}]}`)

// Schema returns the schema for LoanAppParameters.
func (o *LoanAppParameters) Schema() avro.Schema {
	return schemaLoanAppParameters
}

// Unmarshal decodes b into the receiver.
func (o *LoanAppParameters) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *LoanAppParameters) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
