// Code generated by avro/gen. DO NOT EDIT.
package figchain

import (
	"github.com/hamba/avro/v2"
)

// FraudCheckParameters is a generated struct.
type FraudCheckParameters struct {
	FailThreshold int     `avro:"FailThreshold" json:"fail_threshold" yaml:"FailThreshold"`
	Revision      *string `avro:"revision" json:"revision" yaml:"Revision"`
}

var schemaFraudCheckParameters = avro.MustParse(`{"name":"io.figchain._29dc9532_b13e_4b09_bc86_58427fa3f35d.fraud.FraudCheckParameters","type":"record","fields":[{"name":"FailThreshold","type":"int"},{"name":"revision","type":["null","string"]}]}`)

// Schema returns the schema for FraudCheckParameters.
func (o *FraudCheckParameters) Schema() avro.Schema {
	return schemaFraudCheckParameters
}

// Unmarshal decodes b into the receiver.
func (o *FraudCheckParameters) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *FraudCheckParameters) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
