// Code generated by avro/gen. DO NOT EDIT.
package figchain

import (
	"github.com/hamba/avro/v2"
)

// Test is a generated struct.
type Test struct {
	Test string `avro:"test" json:"test" yaml:"Test"`
}

var schemaTest = avro.MustParse(`{"name":"io.figchain.schema.test.test","type":"record","fields":[{"name":"test","type":"string"}]}`)

// Schema returns the schema for Test.
func (o *Test) Schema() avro.Schema {
	return schemaTest
}

// Unmarshal decodes b into the receiver.
func (o *Test) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *Test) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
